//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.11 at 03:53:33 AM MSK 
//


package com.elyashevich.library.entity.paper;

import javafx.beans.property.DoubleProperty;
import javafx.beans.property.SimpleDoubleProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

import javax.annotation.Generated;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.io.Serializable;
import java.util.Objects;


/**
 * <p>Java class for paperEdition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="paperEdition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="title" type="{http://www.example.com/papers}title"/>
 *         &lt;element name="description" type="{http://www.example.com/papers}description"/>
 *         &lt;element name="periodicity" type="{http://www.example.com/papers}periodicity"/>
 *         &lt;element name="price" type="{http://www.example.com/papers}price"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="category" default="newspaper">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="newspaper"/>
 *             &lt;enumeration value="magazine"/>
 *             &lt;enumeration value="book"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "paperEdition", propOrder = {
    "title",
    "description",
    "periodicity",
    "price"
})
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-03-11T03:53:33+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
public class PaperEdition implements Serializable, Cloneable{
    static final long serialVersionUID = 1337L;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-03-11T03:53:33+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String title;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-03-11T03:53:33+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String description;
    @XmlSchemaType(name = "positiveInteger")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-03-11T03:53:33+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected int periodicity;
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-03-11T03:53:33+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected double price;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-03-11T03:53:33+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String id;
    @XmlAttribute(name = "category")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-03-11T03:53:33+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String category;


    public PaperEdition() {
        this("Title", 1.23, 1, "book", "Paper edition");
    }

    public PaperEdition(String title, Double price, Integer periodicity, String type, String description) {
        this.title = title;
        this.price = price;
        this.periodicity = periodicity;
        this.category = type;
        this.description = description;
    }

    public StringProperty titleProperty() {
        return new SimpleStringProperty(title);
    }

    public DoubleProperty getPriceProperty() {
        return new SimpleDoubleProperty(price);
    }
    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-03-11T03:53:33+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-03-11T03:53:33+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-03-11T03:53:33+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-03-11T03:53:33+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the periodicity property.
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-03-11T03:53:33+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public int getPeriodicity() {
        return periodicity;
    }

    /**
     * Sets the value of the periodicity property.
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-03-11T03:53:33+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setPeriodicity(int value) {
        this.periodicity = value;
    }

    /**
     * Gets the value of the price property.
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-03-11T03:53:33+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public double getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-03-11T03:53:33+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setPrice(double value) {
        this.price = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-03-11T03:53:33+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-03-11T03:53:33+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setId(String value) {
        System.out.println("Set id: ");
        this.id = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-03-11T03:53:33+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getCategory() {
        if (category == null) {
            return "newspaper";
        } else {
            return category;
        }
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-03-11T03:53:33+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setCategory(String value) {
        this.category = value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof PaperEdition)) return false;
        PaperEdition that = (PaperEdition) o;
        return Objects.equals(id, that.id);
    }

    @Override
    public int hashCode() {

        return Objects.hash(id);
    }

    @Override
    public String toString() {
        return "PaperEdition{" +
                "title='" + title + '\'' +
                ", description='" + description + '\'' +
                ", periodicity=" + periodicity +
                ", price=" + price +
                ", id='" + id + '\'' +
                ", category='" + category + '\'' +
                '}';
    }
}
