//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.11 at 03:53:33 AM MSK 
//


package com.elyashevich.library.entity.paper;

import javax.annotation.Generated;
import javax.xml.bind.annotation.*;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.example.com/papers}paperEdition" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "paperEdition"
})
@XmlRootElement(name = "papers")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-03-11T03:53:33+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
public class PaperEditionList implements Serializable{
    static final long serialVersionUID = 1336L;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-03-11T03:53:33+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected List<PaperEdition> paperEdition;

    /**
     * Gets the value of the paperEdition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paperEdition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPaperEdition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PaperEdition }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-03-11T03:53:33+03:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public List<PaperEdition> getPaperEdition() {
        if (paperEdition == null) {
            paperEdition = new ArrayList<PaperEdition>();
        }
        return this.paperEdition;
    }

    @Override
    public String toString() {
        return "PaperEditionList{" +
                "paperEdition=" + paperEdition +
                '}';
    }
}
